"""Typed Vulners API response models."""

from .archive import ArchiveRecord
from .audit import (
    AuditAdvisory,
    AuditMatch,
    AuditSoftware,
    CVEAffectedCPE,
    CVEAffectedPackage,
    CVEAuditResult,
    KBAuditResult,
    LegacyAuditResult,
    PackageAuditIssue,
    PackageAuditResult,
    SBOMAuditResult,
    SBOMComponent,
    SmartAuditResult,
    WindowsSoftware,
)
from .documents import BulletinReferences, BulletinWithReferences, KBSeeds
from .misc import CPEMatch, STIXBundle, STIXObject
from .reports import HostVulnsRow, IPSummaryRow, ScanListRow, VulnsListRow, VulnsSummaryRow
from .search import (
    HistoryEntry,
    SearchDocument,
    SearchPage,
    WebVulnerability,
    WebVulnerabilityResult,
)
from .subscriptions import (
    EmailSubscription,
    GenericHostSubscriptionQuery,
    LinuxAuditSubscriptionQuery,
    LinuxHostSubscriptionQuery,
    LuceneSubscriptionQuery,
    PollingDelivery,
    PollingSubscription,
    PollingSubscriptionDelivery,
    SoftwareSubscriptionQuery,
    Subscription,
    SubscriptionDelivery,
    SubscriptionID,
    SubscriptionQuery,
    WebhookSubscriptionDelivery,
    WindowsHostSubscriptionQuery,
)

__all__ = [
    "ArchiveRecord",
    "AuditAdvisory",
    "AuditMatch",
    "AuditSoftware",
    "BulletinReferences",
    "BulletinWithReferences",
    "CPEMatch",
    "CVEAffectedCPE",
    "CVEAffectedPackage",
    "CVEAuditResult",
    "EmailSubscription",
    "GenericHostSubscriptionQuery",
    "HistoryEntry",
    "HostVulnsRow",
    "IPSummaryRow",
    "KBAuditResult",
    "KBSeeds",
    "LegacyAuditResult",
    "LinuxAuditSubscriptionQuery",
    "LinuxHostSubscriptionQuery",
    "LuceneSubscriptionQuery",
    "PackageAuditIssue",
    "PackageAuditResult",
    "PollingDelivery",
    "PollingSubscription",
    "PollingSubscriptionDelivery",
    "SBOMAuditResult",
    "SBOMComponent",
    "STIXBundle",
    "STIXObject",
    "ScanListRow",
    "SearchDocument",
    "SearchPage",
    "SmartAuditResult",
    "SoftwareSubscriptionQuery",
    "Subscription",
    "SubscriptionDelivery",
    "SubscriptionID",
    "SubscriptionQuery",
    "VulnsListRow",
    "VulnsSummaryRow",
    "WebVulnerability",
    "WebVulnerabilityResult",
    "WebhookSubscriptionDelivery",
    "WindowsHostSubscriptionQuery",
    "WindowsSoftware",
]
